### ISSUE TITLE
Add conan version support 

### ISSUE THREAD

**Issue by a4z** [turtlebrowser/get-conan#1]
Thanks for this github action!

Would it be possible to add a way to install conan with a certain/wanted version ?

Because sometimes, with latest, new versions arrive that needs some adoption, and getting that by surprise is not always optimal. Because that mostly happens when it should not happen, and not when time to do the adoption is available :-)

**Comment by Adnn** [comment]
That is a good point. As of today, conan 1.51.2 was published and is now grabbed by the action. Sadly, this new version breaks the build of boost/1.79.0, bringing our whole CI to its knees.

**Comment by a4z** [comment]
Since I am not alone requesting the feature, a PR is up :-)
