### ISSUE TITLE
Problem using installed by default Conan 2.0

### ISSUE THREAD

**Issue by igormironchik** [turtlebrowser/get-conan#7]
Today `Conan` 2.0 has been released. And all my workflows that uses:

```yaml
- name: Install Conan
  id: conan
  uses: turtlebrowser/get-conan@main
```

Failes with:

```
Run conan install . -s build_type=Debug
ERROR: The default build profile '/home/runner/.conan2/profiles/default' doesn't exist.
You need to create a default profile (type 'conan profile detect' command)
or specify your own profile with '--profile:build=<myprofile>'
Error: Process completed with exit code 1.
```

Not sure which this issue is, I post it here, but locally on my `Ubuntu` after upgrade to `Conan` 2.0 I don't see any problems.

**Comment by arman-oganesyan** [comment]
I've faced the same issue, while ~2 weeks ago within the same pipeline I didn't face the issue.

**Comment by patricia-gallardo** [comment]
You can try using the version parameter
```
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 1.50.0
```

**Comment by igormironchik** [comment]
> You can try using the version parameter
> 
> ```
>     - name: Install Conan
>       id: conan
>       uses: turtlebrowser/get-conan@main
>       with:
>         version: 1.50.0
> ```

Sure, this is exactly what I did. But it's an issue all the same. It should be fixed.

**Comment by patricia-gallardo** [comment]
This action just installs conan - which profile and how that is done should probably be handled in the build pipeline.

**Comment by arman-oganesyan** [comment]
I also fixed the issue by providing conan version. Looks like some changes in 2.0 were made, so the behavior now is different. Default profile can be detected using `conan profile detect`. @patricia-gallardo's point of view makes sense.
